from State import *
alabama = JustFatState("Alabama", [])
arizona = JustThinState("Arizona", [])
arkansas = NeutralState("Arkansas", [])
california = LittleThinState("California", [])
colorado = VeryThinState("Colorado", [])
connecticut = JustThinState("Connecticut", [])
delaware = QuiteFatState("Delaware", [])
florida = JustFatState("Florida", [])
georgia = JustThinState("Georgia", [])
idaho = LittleThinState("Idaho", [])
illinois = LittleFatState("Illinois", [])
indiana = MediumFatState("Indiana", [])
iowa = LittleFatState("Iowa", [])
kansas = NeutralState("Kansas", [])
kentucky = LittleFatState("Kentucky", [])
louisiana = LittleFatState("Louisiana", [])
maine = JustThinState("Maine", [])
maryland = JustThinState("Maryland", [])
massachusetts = JustThinState("Massachusetts", [])
michigan = MediumFatState("Michigan", [])
minnesota = JustThinState("Minnesota", [])
mississippi = QuiteFatState("Mississippi", [])
missouri = JustFatState("Missouri", [])
montana = MediumThinState("Montana", [])
nebraska = JustFatState("Nebraska", [])
nevada = NeutralState("Nevada", [])
new_hampshire = LittleThinState("New Hampshire", [])
new_jersey = NeutralState("New Jersey", [])
new_mexico = MediumThinState("New Mexico", [])
new_york = LittleThinState("New York", [])
north_carolina = LittleFatState("North Carolina", [])
north_dakota = JustFatState("North Dakota", [])
ohio = JustFatState("Ohio", [])
oklahoma = JustThinState("Oklahoma", [])
oregon = JustFatState("Oregon", [])
pennsylvania = MediumFatState("Pennsylvania", [])
rhode_island = JustThinState("Rhode Island", [])
south_carolina = LittleFatState("South Carolina", [])
south_dakota = JustThinState("South Dakota", [])
tennessee = JustFatState("Tennessee", [])
texas = JustThinState("Texas", [])
utah = MediumThinState("Utah", [])
vermont = JustThinState("Vermont", [])
virginia = JustFatState("Virginia", [])
washington = JustThinState("Washington", [])
west_virginia = MediumFatState("West Virginia", [])
wisconsin = JustFatState("Wisconsin", [])
wyoming = NeutralState("Wyoming", [])

# Have to add the bordering states after, otherwise we reference states before creating them.
alabama.add_border_states([florida, mississippi, georgia, tennessee])
arizona.add_border_states([california, utah, new_mexico, colorado, nevada])
arkansas.add_border_states([mississippi, louisiana, texas, missouri, tennessee, oklahoma])
california.add_border_states([arizona, nevada, oregon])
colorado.add_border_states([arizona, new_mexico, oklahoma, kansas, nebraska, wyoming, utah])
connecticut.add_border_states([massachusetts, rhode_island, new_york])
delaware.add_border_states([new_jersey, pennsylvania, maryland])
florida.add_border_states([alabama, georgia])
georgia.add_border_states([florida, alabama, south_carolina, tennessee, north_carolina])
idaho.add_border_states([montana, washington, oregon, nevada, utah, wyoming])
illinois.add_border_states([indiana, kentucky, missouri, iowa, wisconsin])
indiana.add_border_states([michigan, illinois, kentucky, ohio])
iowa.add_border_states([minnesota, wisconsin, illinois, missouri, nebraska, south_dakota])
kansas.add_border_states([nebraska, missouri, oklahoma, colorado])
kentucky.add_border_states([west_virginia, missouri, oklahoma, colorado])
louisiana.add_border_states([mississippi, arkansas, texas])
maine.add_border_states([new_hampshire])
maryland.add_border_states([delaware, virginia, west_virginia, pennsylvania])
massachusetts.add_border_states([rhode_island, new_hampshire, vermont, connecticut, new_york])
michigan.add_border_states([indiana, ohio, wisconsin])
minnesota.add_border_states([wisconsin, iowa, south_dakota, north_dakota])
mississippi.add_border_states([louisiana, arkansas, alabama, tennessee])
missouri.add_border_states([arkansas, kentucky, kansas, iowa, illinois, nebraska, tennessee, oklahoma])
montana.add_border_states([idaho, wyoming, north_dakota, south_dakota])
nebraska.add_border_states([missouri, kansas, iowa, colorado, wyoming, south_dakota])
nevada.add_border_states([idaho, california, arizona, utah, oregon])
new_hampshire.add_border_states([maine, massachusetts, vermont])
new_jersey.add_border_states([delaware, new_york, pennsylvania])
new_mexico.add_border_states([arizona, utah, colorado, texas, oklahoma])
new_york.add_border_states([new_jersey, connecticut, massachusetts, pennsylvania, vermont])
north_carolina.add_border_states([georgia, tennessee, virginia, south_carolina])
north_dakota.add_border_states([minnesota, south_dakota, montana])
ohio.add_border_states([indiana, kentucky, michigan, pennsylvania, west_virginia])
oklahoma.add_border_states([kansas, colorado, new_mexico, texas, missouri, arkansas])
oregon.add_border_states([washington, idaho, nevada, colorado])
pennsylvania.add_border_states([delaware, maryland, new_jersey, new_york, ohio, west_virginia])
rhode_island.add_border_states([massachusetts, connecticut])
south_carolina.add_border_states([north_carolina, georgia])
south_dakota.add_border_states([north_dakota, minnesota, iowa, nebraska, wyoming, montana])
tennessee.add_border_states([alabama, arkansas, georgia, kentucky, mississippi, missouri, north_carolina, virginia])
texas.add_border_states([arkansas, louisiana, new_mexico, oklahoma])
utah.add_border_states([arizona, colorado, idaho, nevada, new_mexico, wyoming])
vermont.add_border_states([massachusetts, new_hampshire, new_york])
virginia.add_border_states([kentucky, maryland, ohio, pennsylvania, virginia])
washington.add_border_states([idaho, oregon])
west_virginia.add_border_states([kentucky, maryland, ohio, pennsylvania, virginia])
wisconsin.add_border_states([illinois, iowa, michigan, minnesota])
wyoming.add_border_states([colorado, idaho, montana, nebraska, south_dakota, utah])

